#! /bin/sh
# preinst script for uim
#
# see: dh_installdeb(1)

set -e

case "$1" in
    upgrade)
	if which uim-module-manager >/dev/null 2>&1; then
		if dpkg --compare-versions "$2" le-nl "1:1.8.6+gh20161003.0.d63dadd-5~"; then
			uim-module-manager --unregister anthy --path /var/lib/uim
		fi
	fi
    ;;

    install|abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
