/*===========================================================================
 *  Filename : functable-r5rs-deep-cadrs.c
 *  About    : Built-in function table
 *             This file is auto-generated by build_func_table.rb
 *
 *  Copyright (C) 2005-2006 Kazuki Ohta <mover AT hct.zaq.ne.jp>
 *  Copyright (c) 2007-2008 SigScheme Project <uim-en AT googlegroups.com>
 *
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  1. Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *  2. Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *  3. Neither the name of authors nor the names of its contributors
 *     may be used to endorse or promote products derived from this software
 *     without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS
 *  IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 *  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
===========================================================================*/

#include <stddef.h>

#include "sigscheme.h"


static const struct scm_func_registration_info scm_functable_r5rs_deep_cadrs[] = {
    /* deep-cadrs.c */
    { "caaar", (ScmFuncType)scm_p_caaar, SCM_PROCEDURE_FIXED_1 },
    { "caadr", (ScmFuncType)scm_p_caadr, SCM_PROCEDURE_FIXED_1 },
    { "cadar", (ScmFuncType)scm_p_cadar, SCM_PROCEDURE_FIXED_1 },
    { "cdaar", (ScmFuncType)scm_p_cdaar, SCM_PROCEDURE_FIXED_1 },
    { "cdadr", (ScmFuncType)scm_p_cdadr, SCM_PROCEDURE_FIXED_1 },
    { "cddar", (ScmFuncType)scm_p_cddar, SCM_PROCEDURE_FIXED_1 },
    { "caaaar", (ScmFuncType)scm_p_caaaar, SCM_PROCEDURE_FIXED_1 },
    { "caaadr", (ScmFuncType)scm_p_caaadr, SCM_PROCEDURE_FIXED_1 },
    { "caadar", (ScmFuncType)scm_p_caadar, SCM_PROCEDURE_FIXED_1 },
    { "caaddr", (ScmFuncType)scm_p_caaddr, SCM_PROCEDURE_FIXED_1 },
    { "cadaar", (ScmFuncType)scm_p_cadaar, SCM_PROCEDURE_FIXED_1 },
    { "cadadr", (ScmFuncType)scm_p_cadadr, SCM_PROCEDURE_FIXED_1 },
    { "caddar", (ScmFuncType)scm_p_caddar, SCM_PROCEDURE_FIXED_1 },
    { "cadddr", (ScmFuncType)scm_p_cadddr, SCM_PROCEDURE_FIXED_1 },
    { "cdaaar", (ScmFuncType)scm_p_cdaaar, SCM_PROCEDURE_FIXED_1 },
    { "cdaadr", (ScmFuncType)scm_p_cdaadr, SCM_PROCEDURE_FIXED_1 },
    { "cdadar", (ScmFuncType)scm_p_cdadar, SCM_PROCEDURE_FIXED_1 },
    { "cdaddr", (ScmFuncType)scm_p_cdaddr, SCM_PROCEDURE_FIXED_1 },
    { "cddaar", (ScmFuncType)scm_p_cddaar, SCM_PROCEDURE_FIXED_1 },
    { "cddadr", (ScmFuncType)scm_p_cddadr, SCM_PROCEDURE_FIXED_1 },
    { "cdddar", (ScmFuncType)scm_p_cdddar, SCM_PROCEDURE_FIXED_1 },
    { "cddddr", (ScmFuncType)scm_p_cddddr, SCM_PROCEDURE_FIXED_1 },

    { NULL, NULL, SCM_FUNCTYPE_INVALID }
};
